{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\ntest_example.py:16: AssertionError"}, "start": 1592389159445, "stop": 1592389159445, "uuid": "3922bcb7-f2e3-4f84-8f5e-aeed8378d925", "historyId": "fba9785fde37e8665e5a8ebfe7bdf2af", "testCaseId": "54b9d8c0667a2e59bcf8f362e48cb8d3", "fullName": "test_example#test_answer", "labels": [{"name": "suite", "value": "test_example"}, {"name": "host", "value": "R10459"}, {"name": "thread", "value": "23444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_example"}]}